# Generated by Django 4.2.4 on 2024-11-19 07:40

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('skylineFacade', '0005_majorprojects_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('project', models.CharField(blank=True, max_length=1000, null=True)),
                ('scope', models.CharField(blank=True, max_length=1000, null=True)),
                ('facede_materials', models.CharField(blank=True, max_length=1000, null=True)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('description', tinymce.models.HTMLField(null=True)),
                ('featured_image', models.ImageField(null=True, upload_to='project_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='skylineFacade.services')),
            ],
        ),
    ]
