# Generated by Django 4.2.4 on 2024-11-19 07:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('skylineFacade', '0006_services_serviceimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='services',
            name='description',
        ),
        migrations.RemoveField(
            model_name='services',
            name='facede_materials',
        ),
        migrations.RemoveField(
            model_name='services',
            name='project',
        ),
        migrations.RemoveField(
            model_name='services',
            name='scope',
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='description',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
