# Generated by Django 4.2.4 on 2024-11-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skylineFacade', '0007_remove_serviceimage_caption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceimage',
            name='description',
        ),
    ]
