# Generated by Django 4.2.4 on 2024-11-21 09:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('skylineFacade', '0008_remove_serviceimage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='description',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
