# Generated by Django 4.2.4 on 2024-11-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skylineFacade', '0009_services_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='shor_description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
