# Generated by Django 4.2.4 on 2024-11-21 11:02

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('skylineFacade', '0013_alter_blogpost_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='health_safety',
            name='description',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='majorprojects',
            name='description',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
