# Generated by Django 4.2.4 on 2024-11-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skylineFacade', '0014_alter_blogpost_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='short_description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
