# Generated by Django 4.2.4 on 2024-11-23 10:17

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('skylineFacade', '0017_alter_blogpost_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('featured_image', models.ImageField(null=True, upload_to='product_images/')),
                ('short_description', models.CharField(max_length=500, null=True)),
                ('description', tinymce.models.HTMLField(null=True)),
            ],
        ),
    ]
